import requests
import json
import os

from dotenv import load_dotenv
from pathlib import Path

from web3 import Web3

# Load environment variables from .env
load_dotenv()

# Initialize Web3 with Ganache or other HTTP provider
w3 = Web3(Web3.HTTPProvider('http://127.0.0.1:7545'))

# Headers for Pinata API
headers = {
    "Content-Type": "application/json",
    "pinata_api_key": os.getenv("PINATA_API_KEY"),
    "pinata_secret_api_key": os.getenv("PINATA_SECRET_API_KEY"),
}

# Load the smart contract
def initContract():
    # 1. Point to the correct ABI file generated by Truffle
    abi_path = Path("build/contracts/KYCContract.json")
    
    with open(abi_path) as json_file:
        # 2. The ABI is a specific key inside the JSON artifact
        contract_json = json.load(json_file)
        abi = contract_json['abi']

    contract_address = os.getenv("CONTRACT_ADDRESS")
    if not contract_address:
        raise ValueError("Missing CONTRACT_ADDRESS in .env file")
    
    return w3.eth.contract(address=contract_address, abi=abi)

# Convert data to Pinata-compatible JSON format
def convertDataToJSON(first_name, last_name, dob, age, email, nationality, occupation, zkp_proof, end_date):
    data = {
        "name": "KYC Report",
        "first_name": first_name,
        "last_name": last_name,
        "date_of_birth": dob,
        "age": age,
        "email": email,
        "nationality": nationality,
        "occupation": occupation,
        "zkp_proof": zkp_proof,
        "end_date": end_date
    }
    return data

def add_json_to_local_ipfs(json_data):
    files = {
        'file': ('data.json', json.dumps(json_data))
    }
    # Use IPFS Desktop API port 5001
    response = requests.post('http://127.0.0.1:5001/api/v0/add', files=files)
    response.raise_for_status()
    cid = response.json()['Hash']
    return cid
